### ISSUE TITLE
Update to neomutt 2024-10-02

### ISSUE THREAD

**Issue by flatcap** [neomutt/vim#1]
@avidseeker
Thanks :heart: for your updates to `neomuttrc.vim`.
Sorry I wasn't around to review them; I was on a 3 month hiking expedition!

I've merged your fixes and given the file a thorough review (and tidy).
The results are in the [[neomutt]](https://github.com/neomutt/vim/tree/neomutt) branch.

I'll give it a bit of a test over the next few days,
and if all goes well, below is what I'll to submit to vim.

If you have time to take a look, that'd be appreciated.

Thanks!

---

- Update `syntax/neomuttrc.vim` to the latest version
- Add `syntax/neomuttlog.vim` to handle NeoMutt log files

The first 3 commits perform some tidying up of `neomuttrc.vim`
They make **no functional changes**.

- fe5bb737c neomutt: reorder some definitions
- c9c180609 neomutt: tidy whitespace
- 1fd9fe3b8 neomutt: rename some symbols
- 015651956 neomutt: update to release 2024-10-02
- ce9a3f93d neomutt: add neomuttlog syntax

**Comment by flatcap** [comment]
Submitted to Vim, https://github.com/vim/vim/pull/15858

**Comment by avidseeker** [comment]
Dear Richard,

I hope you had a great hike.

Unfortunately, I didn't have the time, but thank you for the update, and thank you for your contributions in Neomutt. Glad my simple changes helped.

Best,
-- Avid Seeker

**Comment by flatcap** [comment]
Hi Avid Seeker,

> I hope you had a great hike.

It was fantastic, thanks!
The very North East of Scotland's coast, in particular.

> I didn't have the time

no worries

> Glad my simple changes helped.

They did, thanks.

However, there's one annoying problem I haven't managed to fix.

The `color` command accepts _attributes_, e.g. `bold`, but it upsets the Vim highlighting.
See [`color3.rc`](https://github.com/neomutt/neomutt.vim/blob/main/tests/color3.rc) -- in the newly added `tests/` dir.

*If* you have some time to spare, and you're interested that'd be brilliant.

Thanks!

---

You can also find me on IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))
